const dns = require('dns');
dns.setServers(['8.8.8.8', '8.8.4.4']);

const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('./models/Product'); // Ensure this path points to your Product Model
const User = require('./models/User'); // Optional: If you want to link products to an admin

dotenv.config();

// --- THE DATA ---
const products = [
  // ==================== 1. ELECTRONICS (13 Products) ====================
  {
    name: 'Sony Alpha a7 IV',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    description: '33MP full-frame mirrorless camera for professionals.',
    brand: 'Sony',
    category: 'Electronics',
    price: 2498.00,
    countInStock: 8,
    rating: 4.9,
    numReviews: 20,
  },
  {
    name: 'MacBook Pro M3 Max',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca4?auto=format&fit=crop&w=800&q=80',
    description: 'Mind-blowing performance with the M3 Max chip. Space Black.',
    brand: 'Apple',
    category: 'Electronics',
    price: 2499.00,
    countInStock: 5,
    rating: 5.0,
    numReviews: 20,
  },
  {
    name: 'DJI Mavic 3 Cine',
    image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=800&q=80',
    description: 'Professional drone with 4/3 CMOS Hasselblad camera.',
    brand: 'DJI',
    category: 'Electronics',
    price: 4999.00,
    countInStock: 3,
    rating: 4.8,
    numReviews: 12,
  },
  {
    name: 'Marshall Stanmore III',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80',
    description: 'Legendary sound with a wider soundstage. Vintage design.',
    brand: 'Marshall',
    category: 'Electronics',
    price: 379.00,
    countInStock: 15,
    rating: 4.7,
    numReviews: 45,
  },
  {
    name: 'PlayStation 5 Console',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=800&q=80',
    description: 'Experience lightning-fast loading and 3D audio.',
    brand: 'Sony',
    category: 'Electronics',
    price: 499.00,
    countInStock: 25,
    rating: 4.9,
    numReviews: 150,
  },
  {
    name: 'Samsung Odyssey Neo G9',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    description: '49-inch curved gaming monitor with Quantum Mini-LED.',
    brand: 'Samsung',
    category: 'Electronics',
    price: 1299.99,
    countInStock: 6,
    rating: 4.6,
    numReviews: 18,
  },
  {
    name: 'Razer BlackWidow V4',
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80',
    description: 'Mechanical gaming keyboard with green switches and Chroma RGB.',
    brand: 'Razer',
    category: 'Electronics',
    price: 169.99,
    countInStock: 30,
    rating: 4.5,
    numReviews: 60,
  },
  {
    name: 'GoPro HERO12 Black',
    image: 'https://images.unsplash.com/photo-1566418342442-7776d337a723?auto=format&fit=crop&w=800&q=80',
    description: 'Incredible image quality, even better HyperSmooth video stabilization.',
    brand: 'GoPro',
    category: 'Electronics',
    price: 399.00,
    countInStock: 20,
    rating: 4.7,
    numReviews: 40,
  },
  {
    name: 'iPad Pro 12.9"',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    description: 'The ultimate iPad experience with the astonishing M2 chip.',
    brand: 'Apple',
    category: 'Electronics',
    price: 1099.00,
    countInStock: 12,
    rating: 4.8,
    numReviews: 35,
  },
  {
    name: 'Logitech MX Master 3S',
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=800&q=80',
    description: 'Performance wireless mouse with ultra-fast scrolling.',
    brand: 'Logitech',
    category: 'Electronics',
    price: 99.99,
    countInStock: 50,
    rating: 4.9,
    numReviews: 200,
  },
  {
    name: 'Sonos Arc Soundbar',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    description: 'Premium smart soundbar for TV, movies, music, and more.',
    brand: 'Sonos',
    category: 'Electronics',
    price: 899.00,
    countInStock: 8,
    rating: 4.7,
    numReviews: 25,
  },
  {
    name: 'Canon EOS R5',
    image: 'https://images.unsplash.com/photo-1519638831568-d9897f54ed69?auto=format&fit=crop&w=800&q=80',
    description: 'Professional mirrorless camera with 8K video recording.',
    brand: 'Canon',
    category: 'Electronics',
    price: 3899.00,
    countInStock: 4,
    rating: 4.8,
    numReviews: 10,
  },
  {
    name: 'Nintendo Switch OLED',
    image: 'https://images.unsplash.com/photo-1578303512597-8198dd38ad59?auto=format&fit=crop&w=800&q=80',
    description: '7-inch OLED screen with vivid colors and crisp contrast.',
    brand: 'Nintendo',
    category: 'Electronics',
    price: 349.99,
    countInStock: 40,
    rating: 4.8,
    numReviews: 300,
  },

  // ==================== 2. LIFESTYLE (12 Products) ====================
  {
    name: 'Herschel Little America',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    description: 'A popular mountaineering silhouette for everyday adventures.',
    brand: 'Herschel',
    category: 'Lifestyle',
    price: 109.99,
    countInStock: 30,
    rating: 4.6,
    numReviews: 50,
  },
  {
    name: 'Yeti Rambler 26oz',
    image: 'https://images.unsplash.com/photo-1602143407151-11115cdbf6e0?auto=format&fit=crop&w=800&q=80',
    description: 'Vacuum insulated stainless steel bottle with chug cap.',
    brand: 'Yeti',
    category: 'Lifestyle',
    price: 39.99,
    countInStock: 60,
    rating: 4.9,
    numReviews: 120,
  },
  {
    name: 'Ray-Ban Aviator Classic',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80',
    description: 'Timeless design with G-15 lenses for clarity.',
    brand: 'Ray-Ban',
    category: 'Lifestyle',
    price: 163.00,
    countInStock: 20,
    rating: 4.7,
    numReviews: 45,
  },
  {
    name: 'Moleskine Classic Notebook',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    description: 'Hard cover notebook for creative minds.',
    brand: 'Moleskine',
    category: 'Lifestyle',
    price: 22.95,
    countInStock: 100,
    rating: 4.8,
    numReviews: 80,
  },
  {
    name: 'Lululemon Yoga Mat',
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
    description: 'The reversible mat 5mm for extra cushioning.',
    brand: 'Lululemon',
    category: 'Lifestyle',
    price: 88.00,
    countInStock: 25,
    rating: 4.5,
    numReviews: 35,
  },
  {
    name: 'Nike Air Force 1',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
    description: 'The legend lives on in the Nike Air Force 1 \'07.',
    brand: 'Nike',
    category: 'Lifestyle',
    price: 110.00,
    countInStock: 40,
    rating: 4.7,
    numReviews: 200,
  },
  {
    name: 'Peak Design Tech Pouch',
    image: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=800&q=80',
    description: 'Unrivaled organization for cables and daily gear.',
    brand: 'Peak Design',
    category: 'Lifestyle',
    price: 59.95,
    countInStock: 15,
    rating: 4.8,
    numReviews: 20,
  },
  {
    name: 'Hydro Flask Wide Mouth',
    image: 'https://images.unsplash.com/photo-1602143407151-11115cdbf6e0?auto=format&fit=crop&w=800&q=80',
    description: 'Keeps beverages cold up to 24 hours and hot up to 12.',
    brand: 'Hydro Flask',
    category: 'Lifestyle',
    price: 44.95,
    countInStock: 35,
    rating: 4.6,
    numReviews: 90,
  },
  {
    name: 'Kindle Paperwhite',
    image: 'https://images.unsplash.com/photo-1594980596853-75d7b87f8347?auto=format&fit=crop&w=800&q=80',
    description: 'Now with a 6.8" display and adjustable warm light.',
    brand: 'Amazon',
    category: 'Lifestyle',
    price: 139.99,
    countInStock: 18,
    rating: 4.9,
    numReviews: 300,
  },
  {
    name: 'North Face Nuptse Jacket',
    image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=800&q=80',
    description: 'Retro 1996 design with 700-fill goose down.',
    brand: 'The North Face',
    category: 'Lifestyle',
    price: 320.00,
    countInStock: 10,
    rating: 4.7,
    numReviews: 40,
  },
  {
    name: 'Bellroy Slim Sleeve',
    image: 'https://images.unsplash.com/photo-1627123424574-18bd75f3194c?auto=format&fit=crop&w=800&q=80',
    description: 'A slim leather wallet for the minimalist.',
    brand: 'Bellroy',
    category: 'Lifestyle',
    price: 79.00,
    countInStock: 25,
    rating: 4.5,
    numReviews: 15,
  },
  {
    name: 'Aesop Hand Balm',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    description: 'A rich, readily absorbed moisturizing balm.',
    brand: 'Aesop',
    category: 'Lifestyle',
    price: 31.00,
    countInStock: 40,
    rating: 4.8,
    numReviews: 60,
  },

  // ==================== 3. WEARABLES (13 Products) ====================
  {
    name: 'Apple Watch Ultra 2',
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
    description: 'Rugged titanium case with the brightest display ever.',
    brand: 'Apple',
    category: 'Wearables',
    price: 799.00,
    countInStock: 10,
    rating: 4.9,
    numReviews: 80,
  },
  {
    name: 'Oura Ring Gen 3',
    image: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80',
    description: 'Accurate health tracking wrapped around your finger.',
    brand: 'Oura',
    category: 'Wearables',
    price: 299.00,
    countInStock: 15,
    rating: 4.6,
    numReviews: 40,
  },
  {
    name: 'Meta Quest 3',
    image: 'https://images.unsplash.com/photo-1622979135225-d2ba269fb1ac?auto=format&fit=crop&w=800&q=80',
    description: 'Mixed reality headset with 4K+ Infinite Display.',
    brand: 'Meta',
    category: 'Wearables',
    price: 499.99,
    countInStock: 20,
    rating: 4.7,
    numReviews: 50,
  },
  {
    name: 'Garmin Fenix 7 Pro',
    image: 'https://images.unsplash.com/photo-1551817958-c5b51e79326e?auto=format&fit=crop&w=800&q=80',
    description: 'Ultimate multisport GPS watch with solar charging.',
    brand: 'Garmin',
    category: 'Wearables',
    price: 799.99,
    countInStock: 8,
    rating: 4.8,
    numReviews: 25,
  },
  {
    name: 'Whoop 4.0',
    image: 'https://images.unsplash.com/photo-1576243345690-8e4b72893ea9?auto=format&fit=crop&w=800&q=80',
    description: '24/7 fitness tracker that focuses on recovery.',
    brand: 'Whoop',
    category: 'Wearables',
    price: 239.00,
    countInStock: 30,
    rating: 4.5,
    numReviews: 18,
  },
  {
    name: 'Sony WH-1000XM5',
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80',
    description: 'Noise canceling headphones with crystal clear call quality.',
    brand: 'Sony',
    category: 'Wearables',
    price: 348.00,
    countInStock: 22,
    rating: 4.8,
    numReviews: 100,
  },
  {
    name: 'Samsung Galaxy Watch 6',
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
    description: 'Personalized heart rate zones and sleep coaching.',
    brand: 'Samsung',
    category: 'Wearables',
    price: 299.99,
    countInStock: 18,
    rating: 4.6,
    numReviews: 45,
  },
  {
    name: 'AirPods Pro 2',
    image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80',
    description: 'Up to 2x more Active Noise Cancellation.',
    brand: 'Apple',
    category: 'Wearables',
    price: 249.00,
    countInStock: 50,
    rating: 4.9,
    numReviews: 200,
  },
  {
    name: 'Ray-Ban Meta Smart Glasses',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80',
    description: 'Capture, share, and listen with the new smart glasses collection.',
    brand: 'Ray-Ban',
    category: 'Wearables',
    price: 299.00,
    countInStock: 12,
    rating: 4.4,
    numReviews: 10,
  },
  {
    name: 'Fitbit Charge 6',
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=800&q=80',
    description: 'Premium fitness tracker with Google apps built-in.',
    brand: 'Fitbit',
    category: 'Wearables',
    price: 159.95,
    countInStock: 35,
    rating: 4.5,
    numReviews: 60,
  },
  {
    name: 'Bose QuietComfort Ultra',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    description: 'World-class noise cancellation and breakthrough spatial audio.',
    brand: 'Bose',
    category: 'Wearables',
    price: 429.00,
    countInStock: 10,
    rating: 4.7,
    numReviews: 22,
  },
  {
    name: 'Pixel Watch 2',
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    description: 'Help by Google. Health by Fitbit.',
    brand: 'Google',
    category: 'Wearables',
    price: 349.99,
    countInStock: 15,
    rating: 4.3,
    numReviews: 18,
  },
  {
    name: 'Suunto 9 Peak Pro',
    image: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=800&q=80',
    description: 'Ultra-thin GPS multisport watch with long battery life.',
    brand: 'Suunto',
    category: 'Wearables',
    price: 469.00,
    countInStock: 7,
    rating: 4.6,
    numReviews: 9,
  },

  // ==================== 4. HOUSEHOLD (12 Products) ====================
  {
    name: 'Dyson V15 Detect',
    image: 'https://images.unsplash.com/photo-1558317374-a3594743e9c7?auto=format&fit=crop&w=800&q=80',
    description: 'Powerful cordless vacuum with laser illumination.',
    brand: 'Dyson',
    category: 'Household',
    price: 749.99,
    countInStock: 10,
    rating: 4.8,
    numReviews: 55,
  },
  {
    name: 'Nespresso Vertuo Plus',
    image: 'https://images.unsplash.com/photo-1517080315872-87002066d49a?auto=format&fit=crop&w=800&q=80',
    description: 'Versatile coffee maker for espresso and coffee lovers.',
    brand: 'Nespresso',
    category: 'Household',
    price: 169.00,
    countInStock: 25,
    rating: 4.7,
    numReviews: 120,
  },
  {
    name: 'KitchenAid Artisan Stand Mixer',
    image: 'https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?auto=format&fit=crop&w=800&q=80',
    description: 'Iconic design with 10 speeds for every task.',
    brand: 'KitchenAid',
    category: 'Household',
    price: 449.99,
    countInStock: 8,
    rating: 4.9,
    numReviews: 200,
  },
  {
    name: 'Philips Hue Starter Kit',
    image: 'https://images.unsplash.com/photo-1558002038-10915571499f?auto=format&fit=crop&w=800&q=80',
    description: 'White and Color Ambiance smart light bulbs.',
    brand: 'Philips',
    category: 'Household',
    price: 199.99,
    countInStock: 30,
    rating: 4.6,
    numReviews: 85,
  },
  {
    name: 'Herman Miller Aeron Chair',
    image: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&w=800&q=80',
    description: 'Ergonomic office chair with breathable pellicle mesh.',
    brand: 'Herman Miller',
    category: 'Household',
    price: 1695.00,
    countInStock: 5,
    rating: 4.9,
    numReviews: 40,
  },
  {
    name: 'Breville Barista Express',
    image: 'https://images.unsplash.com/photo-1598516087920-999330922616?auto=format&fit=crop&w=800&q=80',
    description: 'Create third-wave specialty coffee at home.',
    brand: 'Breville',
    category: 'Household',
    price: 749.95,
    countInStock: 12,
    rating: 4.8,
    numReviews: 150,
  },
  {
    name: 'Nest Learning Thermostat',
    image: 'https://images.unsplash.com/photo-1563456001-c3baaf6f6eb8?auto=format&fit=crop&w=800&q=80',
    description: 'Smart thermostat that programs itself to save energy.',
    brand: 'Google',
    category: 'Household',
    price: 249.00,
    countInStock: 20,
    rating: 4.5,
    numReviews: 90,
  },
  {
    name: 'iRobot Roomba j7+',
    image: 'https://images.unsplash.com/photo-1583804822005-72436d6232d3?auto=format&fit=crop&w=800&q=80',
    description: 'Self-emptying robot vacuum that avoids pet waste.',
    brand: 'iRobot',
    category: 'Household',
    price: 799.00,
    countInStock: 10,
    rating: 4.4,
    numReviews: 60,
  },
  {
    name: 'Snake Plant (Sansevieria)',
    image: 'https://images.unsplash.com/photo-1599598425947-d35277eb372a?auto=format&fit=crop&w=800&q=80',
    description: 'Low maintenance indoor plant, great for air purification.',
    brand: 'Nature',
    category: 'Household',
    price: 35.00,
    countInStock: 50,
    rating: 4.8,
    numReviews: 12,
  },
  {
    name: 'Coway Air Purifier',
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&q=80',
    description: 'True HEPA air purifier with air quality monitoring.',
    brand: 'Coway',
    category: 'Household',
    price: 229.99,
    countInStock: 18,
    rating: 4.7,
    numReviews: 100,
  },
  {
    name: 'Le Creuset Dutch Oven',
    image: 'https://images.unsplash.com/photo-1584992236310-6eddd724a4c5?auto=format&fit=crop&w=800&q=80',
    description: 'Enameled cast iron signature round dutch oven, 5.5 qt.',
    brand: 'Le Creuset',
    category: 'Household',
    price: 420.00,
    countInStock: 6,
    rating: 4.9,
    numReviews: 80,
  },
  {
    name: 'Minimalist Desk Lamp',
    image: 'https://images.unsplash.com/photo-1534073828943-f801091a7d58?auto=format&fit=crop&w=800&q=80',
    description: 'Matte black LED desk lamp with adjustable arm.',
    brand: 'Ikea',
    category: 'Household',
    price: 49.99,
    countInStock: 35,
    rating: 4.5,
    numReviews: 25,
  }
];

// --- SEEDING SCRIPT ---
const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGO_URI);
    console.log(`MongoDB Connected: ${conn.connection.host}`);
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

const importData = async () => {
  try {
    await connectDB();

    // 1. Clear existing products
    await Product.deleteMany();
    console.log('Old Data Destroyed...');

    // 2. Insert new products
    await Product.insertMany(products);

    console.log('Data Imported Successfully! 🌱');
    process.exit();
  } catch (error) {
    console.error(`${error}`);
    process.exit(1);
  }
};

const destroyData = async () => {
  try {
    await connectDB();
    await Product.deleteMany();
    console.log('Data Destroyed! 💥');
    process.exit();
  } catch (error) {
    console.error(`${error}`);
    process.exit(1);
  }
};

// Check command line arguments
if (process.argv[2] === '-d') {
  destroyData();
} else {
  importData();
}
